// Auto-generated file. Do not edit manually.
// Generated by scripts/create-getWebpAnimations.js

import { useAnimatedImage } from '@shopify/react-native-skia';

export const useWebpAnimations = () => {
    const activeHealthCahIntro = useAnimatedImage(require('../assets/images/clusters/activeHealthCah_intro.webp'));
    const activeHealthCahLoop = useAnimatedImage(require('../assets/images/clusters/activeHealthCah_loop.webp'));
    const activeHealthCahOutro = useAnimatedImage(require('../assets/images/clusters/activeHealthCah_outro.webp'));
    const architectuurEnDesignCadIntro = useAnimatedImage(require('../assets/images/clusters/architectuurEnDesignCad_intro.webp'));
    const architectuurEnDesignCadLoop = useAnimatedImage(require('../assets/images/clusters/architectuurEnDesignCad_loop.webp'));
    const architectuurEnDesignCadOutro = useAnimatedImage(require('../assets/images/clusters/architectuurEnDesignCad_outro.webp'));
    const bedrijfEnOrganisatieCboIntro = useAnimatedImage(require('../assets/images/clusters/bedrijfEnOrganisatieCbo_intro.webp'));
    const bedrijfEnOrganisatieCboLoop = useAnimatedImage(require('../assets/images/clusters/bedrijfEnOrganisatieCbo_loop.webp'));
    const bedrijfEnOrganisatieCboOutro = useAnimatedImage(require('../assets/images/clusters/bedrijfEnOrganisatieCbo_outro.webp'));
    const businessEnMediaCbmIntro = useAnimatedImage(require('../assets/images/clusters/businessEnMediaCbm_intro.webp'));
    const businessEnMediaCbmLoop = useAnimatedImage(require('../assets/images/clusters/businessEnMediaCbm_loop.webp'));
    const businessEnMediaCbmOutro = useAnimatedImage(require('../assets/images/clusters/businessEnMediaCbm_outro.webp'));
    const clusteroverschrijdendIntro = useAnimatedImage(require('../assets/images/clusters/clusteroverschrijdend_intro.webp'));
    const clusteroverschrijdendLoop = useAnimatedImage(require('../assets/images/clusters/clusteroverschrijdend_loop.webp'));
    const clusteroverschrijdendOutro = useAnimatedImage(require('../assets/images/clusters/clusteroverschrijdend_outro.webp'));
    const designTechnologyArtCdtaIntro = useAnimatedImage(require('../assets/images/clusters/designTechnologyArtCdta_intro.webp'));
    const designTechnologyArtCdtaLoop = useAnimatedImage(require('../assets/images/clusters/designTechnologyArtCdta_loop.webp'));
    const designTechnologyArtCdtaOutro = useAnimatedImage(require('../assets/images/clusters/designTechnologyArtCdta_outro.webp'));
    const digitalArtsAndEntertainmentCdaeIntro = useAnimatedImage(require('../assets/images/clusters/digitalArtsAndEntertainmentCdae_intro.webp'));
    const digitalArtsAndEntertainmentCdaeLoop = useAnimatedImage(require('../assets/images/clusters/digitalArtsAndEntertainmentCdae_loop.webp'));
    const digitalArtsAndEntertainmentCdaeOutro = useAnimatedImage(require('../assets/images/clusters/digitalArtsAndEntertainmentCdae_outro.webp'));
    const informaticaEnTechnologieCitIntro = useAnimatedImage(require('../assets/images/clusters/informaticaEnTechnologieCit_intro.webp'));
    const informaticaEnTechnologieCitLoop = useAnimatedImage(require('../assets/images/clusters/informaticaEnTechnologieCit_loop.webp'));
    const informaticaEnTechnologieCitOutro = useAnimatedImage(require('../assets/images/clusters/informaticaEnTechnologieCit_outro.webp'));
    const lifeSciencesClsIntro = useAnimatedImage(require('../assets/images/clusters/lifeSciencesCls_intro.webp'));
    const lifeSciencesClsLoop = useAnimatedImage(require('../assets/images/clusters/lifeSciencesCls_loop.webp'));
    const lifeSciencesClsOutro = useAnimatedImage(require('../assets/images/clusters/lifeSciencesCls_outro.webp'));
    const mensEnWelzijnCmwIntro = useAnimatedImage(require('../assets/images/clusters/mensEnWelzijnCmw_intro.webp'));
    const mensEnWelzijnCmwLoop = useAnimatedImage(require('../assets/images/clusters/mensEnWelzijnCmw_loop.webp'));
    const mensEnWelzijnCmwOutro = useAnimatedImage(require('../assets/images/clusters/mensEnWelzijnCmw_outro.webp'));
    const schoolOfEducationCseIntro = useAnimatedImage(require('../assets/images/clusters/schoolOfEducationCse_intro.webp'));
    const schoolOfEducationCseLoop = useAnimatedImage(require('../assets/images/clusters/schoolOfEducationCse_loop.webp'));
    const schoolOfEducationCseOutro = useAnimatedImage(require('../assets/images/clusters/schoolOfEducationCse_outro.webp'));
    const schoolOfNursingCsnIntro = useAnimatedImage(require('../assets/images/clusters/schoolOfNursingCsn_intro.webp'));
    const schoolOfNursingCsnLoop = useAnimatedImage(require('../assets/images/clusters/schoolOfNursingCsn_loop.webp'));
    const schoolOfNursingCsnOutro = useAnimatedImage(require('../assets/images/clusters/schoolOfNursingCsn_outro.webp'));
    const smartTechCstIntro = useAnimatedImage(require('../assets/images/clusters/smartTechCst_intro.webp'));
    const smartTechCstLoop = useAnimatedImage(require('../assets/images/clusters/smartTechCst_loop.webp'));
    const smartTechCstOutro = useAnimatedImage(require('../assets/images/clusters/smartTechCst_outro.webp'));
    const sociaalAgogischWerkCsawIntro = useAnimatedImage(require('../assets/images/clusters/sociaalAgogischWerkCsaw_intro.webp'));
    const sociaalAgogischWerkCsawLoop = useAnimatedImage(require('../assets/images/clusters/sociaalAgogischWerkCsaw_loop.webp'));
    const sociaalAgogischWerkCsawOutro = useAnimatedImage(require('../assets/images/clusters/sociaalAgogischWerkCsaw_outro.webp'));

    // Define a strict map to lookup animations by constructed key
    const animationMap: Record<string, ReturnType<typeof useAnimatedImage>> = {
        'activeHealthCahIntro': activeHealthCahIntro,
        'activeHealthCahLoop': activeHealthCahLoop,
        'activeHealthCahOutro': activeHealthCahOutro,

        'architectuurEnDesignCadIntro': architectuurEnDesignCadIntro,
        'architectuurEnDesignCadLoop': architectuurEnDesignCadLoop,
        'architectuurEnDesignCadOutro': architectuurEnDesignCadOutro,

        'bedrijfEnOrganisatieCboIntro': bedrijfEnOrganisatieCboIntro,
        'bedrijfEnOrganisatieCboLoop': bedrijfEnOrganisatieCboLoop,
        'bedrijfEnOrganisatieCboOutro': bedrijfEnOrganisatieCboOutro,

        'businessEnMediaCbmIntro': businessEnMediaCbmIntro,
        'businessEnMediaCbmLoop': businessEnMediaCbmLoop,
        'businessEnMediaCbmOutro': businessEnMediaCbmOutro,

        'clusteroverschrijdendIntro': clusteroverschrijdendIntro,
        'clusteroverschrijdendLoop': clusteroverschrijdendLoop,
        'clusteroverschrijdendOutro': clusteroverschrijdendOutro,

        'designTechnologyArtCdtaIntro': designTechnologyArtCdtaIntro,
        'designTechnologyArtCdtaLoop': designTechnologyArtCdtaLoop,
        'designTechnologyArtCdtaOutro': designTechnologyArtCdtaOutro,

        'digitalArtsAndEntertainmentCdaeIntro': digitalArtsAndEntertainmentCdaeIntro,
        'digitalArtsAndEntertainmentCdaeLoop': digitalArtsAndEntertainmentCdaeLoop,
        'digitalArtsAndEntertainmentCdaeOutro': digitalArtsAndEntertainmentCdaeOutro,

        'informaticaEnTechnologieCitIntro': informaticaEnTechnologieCitIntro,
        'informaticaEnTechnologieCitLoop': informaticaEnTechnologieCitLoop,
        'informaticaEnTechnologieCitOutro': informaticaEnTechnologieCitOutro,

        'lifeSciencesClsIntro': lifeSciencesClsIntro,
        'lifeSciencesClsLoop': lifeSciencesClsLoop,
        'lifeSciencesClsOutro': lifeSciencesClsOutro,

        'mensEnWelzijnCmwIntro': mensEnWelzijnCmwIntro,
        'mensEnWelzijnCmwLoop': mensEnWelzijnCmwLoop,
        'mensEnWelzijnCmwOutro': mensEnWelzijnCmwOutro,

        'schoolOfEducationCseIntro': schoolOfEducationCseIntro,
        'schoolOfEducationCseLoop': schoolOfEducationCseLoop,
        'schoolOfEducationCseOutro': schoolOfEducationCseOutro,

        'schoolOfNursingCsnIntro': schoolOfNursingCsnIntro,
        'schoolOfNursingCsnLoop': schoolOfNursingCsnLoop,
        'schoolOfNursingCsnOutro': schoolOfNursingCsnOutro,

        'smartTechCstIntro': smartTechCstIntro,
        'smartTechCstLoop': smartTechCstLoop,
        'smartTechCstOutro': smartTechCstOutro,

        'sociaalAgogischWerkCsawIntro': sociaalAgogischWerkCsawIntro,
        'sociaalAgogischWerkCsawLoop': sociaalAgogischWerkCsawLoop,
        'sociaalAgogischWerkCsawOutro': sociaalAgogischWerkCsawOutro,

    };

    const projects = ['activeHealthCah', 'architectuurEnDesignCad', 'bedrijfEnOrganisatieCbo', 'businessEnMediaCbm', 'clusteroverschrijdend', 'designTechnologyArtCdta', 'digitalArtsAndEntertainmentCdae', 'informaticaEnTechnologieCit', 'lifeSciencesCls', 'mensEnWelzijnCmw', 'schoolOfEducationCse', 'schoolOfNursingCsn', 'smartTechCst', 'sociaalAgogischWerkCsaw'];

    return { animationMap, projects };
};
